### ISSUE TITLE
spo抽取

### ISSUE THREAD

**Issue by zgd716** [loujie0822/DeepIE#27]
transformers_multi_label_span   这个目前可以运行抽取百度的spo信息吗?

**Comment by loujie0822** [comment]
具体可参考https://github.com/loujie0822/DeepIE/blob/master/docs/%E5%85%B3%E7%B3%BB%E6%8A%BD%E5%8F%96run%E8%AF%B4%E6%98%8E.md

**Comment by zgd716** [comment]
> 具体可参考https://github.com/loujie0822/DeepIE/blob/master/docs/%E5%85%B3%E7%B3%BB%E6%8A%BD%E5%8F%96run%E8%AF%B4%E6%98%8E.md

ok,tks
