### ISSUE TITLE
新闻内容抽取问题

### ISSUE THREAD

**Issue by zgd716** [loujie0822/DeepIE#46]
大佬好,《Joint Extraction of Entities and Relations Based on a Novel Decomposition Strategy》bert实现和苏剑林的bert4keras信息抽取在百度2019基本f1都在0.82左右,但是真正抽取新闻的时候,使用句子进行切割,效果很不理想,有什么推荐trick?

**Comment by Bingoyue** [comment]
大佬有百度信息抽取任务的数据集麽？能不能提供一份

**Comment by loujie0822** [comment]
给我一个你的邮箱吧😄 loujie0822 邮箱：loujie0822@aliyun.com 签名由 网易邮箱大师 定制 在2020年06月02日 10:10，Bingoyue 写道： 大佬有百度信息抽取任务的数据集麽？能不能提供一份 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by loujie0822** [comment]
使用句子进行切割 具体指的是什么？

**Comment by liutianling** [comment]
@loujie0822 感觉在给你找bug，到处都跑不通，
