### ISSUE TITLE
无法抽取百度2019数据的spo信息

### ISSUE THREAD

**Issue by liutianling** [loujie0822/DeepIE#57]
仔细查看了代码里面的数据读取，代码应该是没有匹配2019年的数据格式，不知道是不是我看错了
run/relation_extraction/etl_span_transformers/data_loader_v2.py, line 212
2019数据的spo['object']已经是个字符串了，没有keys()属性了，
                        for spo_object in spo['object'].keys():
                            if spo['predicate'] in self.spo_conf:
                                label = spo['predicate']
                            else:
                                label = spo['predicate'] + '_' + spo_object
                            spo_dict[self.spo_conf[label]] = spo['object'][spo_object]

**Comment by liutianling** [comment]
# "cpt/baidu_w2v/sgns.target.word-character.char1-2.dynwin5.thr10.neg5.dim300.iter5"
    # 'cpt/baidu_w2v/w2v.txt'
    parser.add_argument('--embedding_file', type=str,
                        default='cpt/baidu_w2v/w2v.txt')
这份词向量能提供下吗？谢谢

**Comment by liutianling** [comment]
这个问题解决了,数据源是数据加载模块的不匹配

**Comment by wenyu332** [comment]
> 这个问题解决了,数据源是数据加载模块的不匹配
你好，请问这个问题是怎么解决的，我也碰到了这个问题。。。

**Comment by ReadyTeresa** [comment]
> 这个问题解决了,数据源是数据加载模块的不匹配
请问怎么解决的
